analyzer:
  exclude:
    - lib/generated/**

  errors:
    missing_return: ignore
    unnecessary_import: ignore
    unused_import: ignore

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
    always_declare_return_types: false
